### ISSUE TITLE
FluentMigration console runner doesn't work with dbtype=Postgres

### ISSUE THREAD

**Issue by vchyzhevskyi** [fluentmigrator/fluentmigrator#993]
Hello,

Today I faced a problem with running the DB migrations on Postgres server using FluentMigration console runner.
Previously we used SQL Server for the database and everything was fine:

```
..\..\..\packages\FluentMigrator.Console.3.1.3\net461\any\Migrate.exe `
	-a .\Migrations.dll `
	-conn "Data Source=.\SQLEXPRESS;Initial Catalog=<db>;Integrated Security=True;" `
	-db SqlServer2014
```

but once, we wanted to run the same migrations (the only schema was changed from `dbo` to `public`) on our Postgres server we start receiving the exception:

```
..\..\..\packages\FluentMigrator.Console.3.1.3\net461\any\Migrate.exe `
	-a .\Migrations.dll `
	-conn "Server=<server>;Database=<db>;User Id=<user>;Password='<pass>';" `
	-db Postgres
```

```
-------------------------------------------------------------------------------
=============================== FluentMigrator ================================
-------------------------------------------------------------------------------
Source Code:
  https://github.com/fluentmigrator/fluentmigrator
Ask For Help:
  https://gitter.im/FluentMigrator/fluentmigrator
-------------------------------------------------------------------------------
Using connection string Server=10.211.55.4;Database=<db>;User Id=<user>;Password=********
!!! Could not load file or assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
!!! +- Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

We're using the latest version of FluentMigration tool (3.1.3) and Postgres server 11. This is not a connectivity problem as I'm able to connect to the Postgres server using other tools.

Do you know what may cause such an exception?

**Comment by fubar-coder** [comment]
This seems like a missing binding redirect. Maybe you're able to use the `dotnet-fm` tool instead?

**Comment by vchyzhevskyi** [comment]
@fubar-coder 

just tested it on v 3.0.0 and with following changes console runner starts working:

```
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.11.0" newVersion="4.0.11.0" />
      </dependentAssembly>
    </assemblyBinding>
```
```
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
    </assemblyBinding>
```

For me it's not necessary to use the latest version of Fluent Migration, however, if you will need additional investigation around this issue please let me know.

**Comment by fubar-coder** [comment]
Should be fixed for the next build. The problem is that the .NET Core assemblies get updated quite often.

**Comment by sumanrajpura** [comment]
Hello,

I am trying to use Console runner 3.2.1  for PostgreSQL 11.5 and still facing this issue. Same is the case for Console runner 3.2.0. Please let me know how can I resolve it.

Thanks.

**Comment by jzabroski** [comment]
I strongly recommend using The InProcess Toolchain for now.  Once .NET Core 3 is released I think we can do a lot to smooth out user experiences related to loading database provider plugins, as .NET Core 3 has a robust plugin api.

The main use case for External Runners (Console, MSBuild) is color streaming.  With MSBuild, you get red blood in the terminal when you make a mistake, so the user experience is way better.  With the Console runner, you can run it say in Octopus Deploy release.
